spring.application.name: api-gateway

server.port: 8080

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts_service/**
          filters:
            - StripPrefix=2

#        - id: connections-service
#          uri: lb://CONNECTIONS-SERVICE
#          predicates:
#            - Path=/api/v1/connections_service/**
#          filters:
#            - StripPrefix=2

